# CDK-Office Production Configuration

# Server configuration
SERVER_HOST=0.0.0.0
SERVER_PORT=8080

# Database configuration
DB_HOST=postgres
DB_PORT=5432
DB_NAME=cdkoffice
DB_USER=cdkoffice
DB_PASSWORD=cdkoffice
DB_SSL_MODE=disable

# Redis configuration
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0

# Dify configuration
DIFY_API_KEY=your_dify_api_key
DIFY_BASE_URL=http://dify:8000

# JWT configuration
JWT_SECRET=your_jwt_secret
JWT_EXPIRATION_TIME=24h

# Logging configuration
LOG_LEVEL=info
LOG_FORMAT=json

# Cache configuration
CACHE_TTL=1h
CACHE_CLEANUP_INTERVAL=10m

# File storage configuration
STORAGE_PATH=/var/lib/cdk-office/storage
MAX_FILE_SIZE=100MB

# Security configuration
CORS_ALLOWED_ORIGINS=*
CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
CORS_ALLOWED_HEADERS=*

# Performance configuration
MAX_CONCURRENT_REQUESTS=1000
REQUEST_TIMEOUT=30s

# Monitoring configuration
ENABLE_METRICS=true
METRICS_PORT=9090